name: Continuous integration
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: production build
        run: npm run build:prod
      - name: run linter typescript
        run: npm run lint:ts
      - name: run linter css
        run: npm run lint:scss
      - name: run unit tests
        run: npm run test:unit
      - name: storybook build
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci